/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsConditionsRouteImport } from './routes/terms-conditions'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShippingPolicyRouteImport } from './routes/shipping-policy'
import { Route as SafariLookbookRouteImport } from './routes/safari-lookbook'
import { Route as ReturnsPolicyRouteImport } from './routes/returns-policy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VerifyEmailTokenRouteImport } from './routes/verify-email.$token'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminSubCategoriesRouteImport } from './routes/admin.sub-categories'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPermissionsRouteImport } from './routes/admin.permissions'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminNewsletterRouteImport } from './routes/admin.newsletter'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLaunchRouteImport } from './routes/admin.launch'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminImportRouteImport } from './routes/admin.import'
import { Route as AdminHomepageRouteImport } from './routes/admin.homepage'
import { Route as AdminFaqsRouteImport } from './routes/admin.faqs'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AccountWishlistRouteImport } from './routes/account.wishlist'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'

const TermsConditionsRoute = TermsConditionsRouteImport.update({
  id: '/terms-conditions',
  path: '/terms-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingPolicyRoute = ShippingPolicyRouteImport.update({
  id: '/shipping-policy',
  path: '/shipping-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SafariLookbookRoute = SafariLookbookRouteImport.update({
  id: '/safari-lookbook',
  path: '/safari-lookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsPolicyRoute = ReturnsPolicyRouteImport.update({
  id: '/returns-policy',
  path: '/returns-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VerifyEmailTokenRoute = VerifyEmailTokenRouteImport.update({
  id: '/verify-email/$token',
  path: '/verify-email/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubCategoriesRoute = AdminSubCategoriesRouteImport.update({
  id: '/sub-categories',
  path: '/sub-categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPermissionsRoute = AdminPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsletterRoute = AdminNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLaunchRoute = AdminLaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqsRoute = AdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AccountWishlistRoute = AccountWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/returns-policy': typeof ReturnsPolicyRoute
  '/safari-lookbook': typeof SafariLookbookRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/shop': typeof ShopRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/launch': typeof AdminLaunchRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sub-categories': typeof AdminSubCategoriesRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/product/$slug': typeof ProductSlugRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/returns-policy': typeof ReturnsPolicyRoute
  '/safari-lookbook': typeof SafariLookbookRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/shop': typeof ShopRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/launch': typeof AdminLaunchRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sub-categories': typeof AdminSubCategoriesRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/product/$slug': typeof ProductSlugRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/returns-policy': typeof ReturnsPolicyRoute
  '/safari-lookbook': typeof SafariLookbookRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/shop': typeof ShopRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/launch': typeof AdminLaunchRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sub-categories': typeof AdminSubCategoriesRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/product/$slug': typeof ProductSlugRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/cart'
    | '/contact'
    | '/privacy-policy'
    | '/returns-policy'
    | '/safari-lookbook'
    | '/shipping-policy'
    | '/shop'
    | '/terms-conditions'
    | '/account/orders'
    | '/account/wishlist'
    | '/admin/analytics'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/faqs'
    | '/admin/homepage'
    | '/admin/import'
    | '/admin/inventory'
    | '/admin/launch'
    | '/admin/login'
    | '/admin/media'
    | '/admin/newsletter'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/permissions'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/sub-categories'
    | '/admin/transactions'
    | '/product/$slug'
    | '/verify-email/$token'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/cart'
    | '/contact'
    | '/privacy-policy'
    | '/returns-policy'
    | '/safari-lookbook'
    | '/shipping-policy'
    | '/shop'
    | '/terms-conditions'
    | '/account/orders'
    | '/account/wishlist'
    | '/admin/analytics'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/faqs'
    | '/admin/homepage'
    | '/admin/import'
    | '/admin/inventory'
    | '/admin/launch'
    | '/admin/login'
    | '/admin/media'
    | '/admin/newsletter'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/permissions'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/sub-categories'
    | '/admin/transactions'
    | '/product/$slug'
    | '/verify-email/$token'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/cart'
    | '/contact'
    | '/privacy-policy'
    | '/returns-policy'
    | '/safari-lookbook'
    | '/shipping-policy'
    | '/shop'
    | '/terms-conditions'
    | '/account/orders'
    | '/account/wishlist'
    | '/admin/analytics'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/faqs'
    | '/admin/homepage'
    | '/admin/import'
    | '/admin/inventory'
    | '/admin/launch'
    | '/admin/login'
    | '/admin/media'
    | '/admin/newsletter'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/permissions'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/sub-categories'
    | '/admin/transactions'
    | '/product/$slug'
    | '/verify-email/$token'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ReturnsPolicyRoute: typeof ReturnsPolicyRoute
  SafariLookbookRoute: typeof SafariLookbookRoute
  ShippingPolicyRoute: typeof ShippingPolicyRoute
  ShopRoute: typeof ShopRoute
  TermsConditionsRoute: typeof TermsConditionsRoute
  ProductSlugRoute: typeof ProductSlugRoute
  VerifyEmailTokenRoute: typeof VerifyEmailTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-conditions': {
      id: '/terms-conditions'
      path: '/terms-conditions'
      fullPath: '/terms-conditions'
      preLoaderRoute: typeof TermsConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-policy': {
      id: '/shipping-policy'
      path: '/shipping-policy'
      fullPath: '/shipping-policy'
      preLoaderRoute: typeof ShippingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safari-lookbook': {
      id: '/safari-lookbook'
      path: '/safari-lookbook'
      fullPath: '/safari-lookbook'
      preLoaderRoute: typeof SafariLookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns-policy': {
      id: '/returns-policy'
      path: '/returns-policy'
      fullPath: '/returns-policy'
      preLoaderRoute: typeof ReturnsPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/verify-email/$token': {
      id: '/verify-email/$token'
      path: '/verify-email/$token'
      fullPath: '/verify-email/$token'
      preLoaderRoute: typeof VerifyEmailTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sub-categories': {
      id: '/admin/sub-categories'
      path: '/sub-categories'
      fullPath: '/admin/sub-categories'
      preLoaderRoute: typeof AdminSubCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/permissions': {
      id: '/admin/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminPermissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/newsletter': {
      id: '/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AdminNewsletterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/launch': {
      id: '/admin/launch'
      path: '/launch'
      fullPath: '/admin/launch'
      preLoaderRoute: typeof AdminLaunchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faqs': {
      id: '/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminFaqsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/wishlist': {
      id: '/account/wishlist'
      path: '/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AccountWishlistRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
  }
}

interface AccountRouteChildren {
  AccountOrdersRoute: typeof AccountOrdersRoute
  AccountWishlistRoute: typeof AccountWishlistRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountOrdersRoute: AccountOrdersRoute,
  AccountWishlistRoute: AccountWishlistRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminFaqsRoute: typeof AdminFaqsRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminImportRoute: typeof AdminImportRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminLaunchRoute: typeof AdminLaunchRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminNewsletterRoute: typeof AdminNewsletterRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPermissionsRoute: typeof AdminPermissionsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubCategoriesRoute: typeof AdminSubCategoriesRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminFaqsRoute: AdminFaqsRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminImportRoute: AdminImportRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminLaunchRoute: AdminLaunchRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminNewsletterRoute: AdminNewsletterRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPermissionsRoute: AdminPermissionsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubCategoriesRoute: AdminSubCategoriesRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ReturnsPolicyRoute: ReturnsPolicyRoute,
  SafariLookbookRoute: SafariLookbookRoute,
  ShippingPolicyRoute: ShippingPolicyRoute,
  ShopRoute: ShopRoute,
  TermsConditionsRoute: TermsConditionsRoute,
  ProductSlugRoute: ProductSlugRoute,
  VerifyEmailTokenRoute: VerifyEmailTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
